khazerium compile done
luloxi/evolution-DAO pull request #2
Opened 2023-04-30 21:49 UTC by scobru

Simplified version of Khazerium.

2023-04-30 22:21 UTC, scobru commented
Implementation ERC20Votes!

2023-05-01 20:08 UTC, luloxi requested changes

2023-05-01 20:08 UTC, luloxi commented on packages/hardhat/contracts/KhaNft.sol
If you increment the _tokenIds, then save the current tokenId, and then log that, you'll be logging the wrong tokenId (the one that's 1 more than the one you want to return

2023-05-01 20:08 UTC, luloxi commented on packages/hardhat/contracts/Khazerium.sol
1. This should be imported on the token contract for this build, not in the Khazerium (Governor contract) itself

import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Votes.sol";

2. The variable "data" on the proposal struct is the calldata for a specific function in function within Khazerium?

What purpose does it serve? What would it call within Khazerium?

3. In case "data" is really needed, it's not included in "getProposal" return statement.

2023-05-01 20:08 UTC, luloxi commented on packages/hardhat/contracts/Khazi.sol
This and Khazerium still should be on the move-to-separate-branch folder, I'll make the branches now so you can commit to the Khazerium one and I can start participating in the development as well

2023-05-01 20:50 UTC, scobru commented on packages/hardhat/contracts/KhaNft.sol
i will fix.

2023-05-01 20:53 UTC, scobru commented on packages/hardhat/contracts/Khazerium.sol
The 'data' variable can be optional, it can be passed if one wants to interact with an external vault or smart contract, transferring ownership to the DAO contract.

2023-05-01 21:38 UTC, luloxi commented on packages/hardhat/contracts/Khazerium.sol
What do you think the contract could do on execution? Can you add some simple contract to interact with, so execution does something else than just minting the NFT?

2023-10-30 23:56 UTC, closed without merging